[package]
name = "brim-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
brim = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
unicode-normalization = "0.1.24"
brim-symbols-macro = { workspace = true }
lazy_static = "1.5.0"
indexmap = { workspace = true }