[package]
name = "brim-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = { workspace = true }
anstream = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }
gethostname = { workspace = true }
terminal_size = { workspace = true }