[package]
name = "brim-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
anstream = { workspace = true }
anstyle = { workspace = true }
anyhow = { workspace = true }
gethostname = { workspace = true }
terminal_size = { workspace = true }
url = { workspace = true }
