[package]
name = "brim-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
brim-ast = { workspace = true }
brim-hir = { workspace = true }
brim-middle = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
