[package]
name = "brim-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
brim-span = { workspace = true }
brim-index = { workspace = true }
indexmap = { workspace = true }
brim-symbols-macro = { workspace = true }
lazy_static = "1.5.0"